config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :members
    resources :comments
  end

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  scope module: :public do
    root to: 'homes#top'
    get "homes/about" => "homes#about"
    resources :tasks do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'search' => 'searches#search'

    get 'members/unsubscribe' => 'members#unsubscribe'
    delete 'members/withdraw' => 'members#withdraw'
    resources :members, only: [:show, :edit, :update] do
      member do
        get "favorites"
      end
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :task

  validates :comment_text, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @comments = Comment.all.page(params[:page]).per(10)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/index.html.erb
<div class="container my-5">
  <div class="text-center">
    <h3>コメント一覧</h3>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>日時</th>
            <th>コメントされた人</th>
            <th>コメントした人</th>
            <th>コメント</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.task.start_time.strftime("%m月%d日 %H:%M") %></td>
            <td><%= comment.task.member.nickname %></td>
            <td><%= comment.member.nickname %></td>
            <td><%= comment.comment_text %></td>
            <td><%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @comments %>
    </div>
  </div>
</div>