config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :members
    resources :comments
  end

  devise_scope :member do
    post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
  end
  devise_for :members,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  scope module: :public do
    root to: 'homes#top'
    get "homes/about" => "homes#about"
    resources :tasks do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    get 'search' => 'searches#search'

    get 'members/unsubscribe' => 'members#unsubscribe'
    delete 'members/withdraw' => 'members#withdraw'
    resources :members, only: [:show, :edit, :update] do
      member do
        get "favorites"
      end
    end
  end


end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_tasks, through: :favorites, source: :task
  has_many :comments, dependent: :destroy

  validates :nickname, presence: true
  validates :email, presence: true

  def already_favorited?(task)
    self.favorites.exists?(task_id: task.id)
  end

  def self.guest
    find_or_create_by!(nickname: 'guestmember' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.nickname = "guestmember"
    end
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @members = Member.all.page(params[:page]).per(10)
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to admin_members_path
  end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController

  def guest_sign_in
    member = Member.guest
    sign_in member
    redirect_to member_path(member), notice: 'guestuserでログインしました。'
  end

end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/destroy.html.erb
<h1>Admin::Members#destroy</h1>
<p>Find me in app/views/admin/members/destroy.html.erb</p>

app/views/admin/members/index.html.erb
<div class="container my-5">
  <div class="text-center">
    <h3>会員一覧</h3>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
        <% @members.each do |member| %>
        <tr>
          <td><%= member.id %></td>
          <td><%= link_to member.nickname, admin_member_path(member.id) %></td>
          <td><%= member.email %></td>
          <td><%= link_to "削除", admin_member_path(member), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @members %>
    </div>
  </div>
</div>